# Generated by Django 5.2 on 2026-09-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
