services:
  web:
    container_name: shop_web
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "7001:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: shop_db
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: shop_redis
    image: redis:8
    volumes:
      - redis_data:/data

  celery_worker:
    container_name: shop_worker
    build:
      context: .
    command: celery -A shop_api worker --loglevel=INFO
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  celery_beat:
    container_name: shop_beat
    build:
      context: .
    command: celery -A shop_api beat --loglevel=INFO
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  flower:
    container_name: shop_flower
    build:
      context: .
    command: celery -A shop_api flower --port=5555
    ports:
      - "5556:5555"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery_worker

volumes:
  postgres_data:
  redis_data: