# Generated by Django 5.2 on 2026-08-25 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 25, 10, 57, 28, 539855, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 25, 10, 57, 28, 539855, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 25, 10, 57, 28, 539855, tzinfo=datetime.timezone.utc)),
        ),
    ]
